"""empty message

Revision ID: 2e35ad0fbac4
Revises: 
Create Date: 2021-06-15 18:07:48.432932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e35ad0fbac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('person_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('Address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('street_number', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('Email',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('Phone',
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('phone_no', sa.String(length=10), nullable=False),
    sa.Column('cell_no', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('phone_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Phone')
    op.drop_table('Email')
    op.drop_table('Address')
    op.drop_table('person')
    # ### end Alembic commands ###
