"""empty message

Revision ID: 4c093335eec4
Revises: 2e35ad0fbac4
Create Date: 2021-06-15 18:13:38.065878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c093335eec4'
down_revision = '2e35ad0fbac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.drop_table('phone')
    op.drop_table('email')

    op.create_table('Address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('street_number', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('Email',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('Phone',
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('cell_no', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('phone_id')
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('email_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], name='email_ibfk_1'),
    sa.PrimaryKeyConstraint('email_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('phone',
    sa.Column('phone_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_no', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('cell_no', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], name='phone_ibfk_1'),
    sa.PrimaryKeyConstraint('phone_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('address',
    sa.Column('address_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('street_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], name='address_ibfk_1'),
    sa.PrimaryKeyConstraint('address_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Phone')
    op.drop_table('Email')
    op.drop_table('Address')
    # ### end Alembic commands ###
